version: "3.7"

services:
  com.knilim.notification.redis:
    image: redis:latest
    container_name: com.knilim.notification
    command: redis-server --requirepass 123456
    ports:
      - "6377:6379"

  com.knilim.offline.redis:
    image: redis:latest
    container_name: com.knilim.offline
    command: redis-server --requirepass 123456
    ports:
      - "6378:6379"

  com.knilim.online.redis:
    image: redis:latest
    container_name: com.knilim.online
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
