// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConnectResponse.proto

package com.knilim.session.data;

public final class ConnectResponseProto {
  private ConnectResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConnectResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConnectResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string Y = 1;</code>
     * @return The y.
     */
    java.lang.String getY();
    /**
     * <code>string Y = 1;</code>
     * @return The bytes for y.
     */
    com.google.protobuf.ByteString
        getYBytes();

    /**
     * <code>repeated bytes offlineMsgs = 2;</code>
     * @return A list containing the offlineMsgs.
     */
    java.util.List<com.google.protobuf.ByteString> getOfflineMsgsList();
    /**
     * <code>repeated bytes offlineMsgs = 2;</code>
     * @return The count of offlineMsgs.
     */
    int getOfflineMsgsCount();
    /**
     * <code>repeated bytes offlineMsgs = 2;</code>
     * @param index The index of the element to return.
     * @return The offlineMsgs at the given index.
     */
    com.google.protobuf.ByteString getOfflineMsgs(int index);
  }
  /**
   * Protobuf type {@code ConnectResponse}
   */
  public  static final class ConnectResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConnectResponse)
      ConnectResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConnectResponse.newBuilder() to construct.
    private ConnectResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConnectResponse() {
      y_ = "";
      offlineMsgs_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConnectResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConnectResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              y_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                offlineMsgs_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              offlineMsgs_.add(input.readBytes());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          offlineMsgs_ = java.util.Collections.unmodifiableList(offlineMsgs_); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.knilim.session.data.ConnectResponseProto.internal_static_ConnectResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.knilim.session.data.ConnectResponseProto.internal_static_ConnectResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.knilim.session.data.ConnectResponseProto.ConnectResponse.class, com.knilim.session.data.ConnectResponseProto.ConnectResponse.Builder.class);
    }

    public static final int Y_FIELD_NUMBER = 1;
    private volatile java.lang.Object y_;
    /**
     * <code>string Y = 1;</code>
     * @return The y.
     */
    public java.lang.String getY() {
      java.lang.Object ref = y_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        y_ = s;
        return s;
      }
    }
    /**
     * <code>string Y = 1;</code>
     * @return The bytes for y.
     */
    public com.google.protobuf.ByteString
        getYBytes() {
      java.lang.Object ref = y_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        y_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OFFLINEMSGS_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.ByteString> offlineMsgs_;
    /**
     * <code>repeated bytes offlineMsgs = 2;</code>
     * @return A list containing the offlineMsgs.
     */
    public java.util.List<com.google.protobuf.ByteString>
        getOfflineMsgsList() {
      return offlineMsgs_;
    }
    /**
     * <code>repeated bytes offlineMsgs = 2;</code>
     * @return The count of offlineMsgs.
     */
    public int getOfflineMsgsCount() {
      return offlineMsgs_.size();
    }
    /**
     * <code>repeated bytes offlineMsgs = 2;</code>
     * @param index The index of the element to return.
     * @return The offlineMsgs at the given index.
     */
    public com.google.protobuf.ByteString getOfflineMsgs(int index) {
      return offlineMsgs_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getYBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, y_);
      }
      for (int i = 0; i < offlineMsgs_.size(); i++) {
        output.writeBytes(2, offlineMsgs_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getYBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, y_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < offlineMsgs_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(offlineMsgs_.get(i));
        }
        size += dataSize;
        size += 1 * getOfflineMsgsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.knilim.session.data.ConnectResponseProto.ConnectResponse)) {
        return super.equals(obj);
      }
      com.knilim.session.data.ConnectResponseProto.ConnectResponse other = (com.knilim.session.data.ConnectResponseProto.ConnectResponse) obj;

      if (!getY()
          .equals(other.getY())) return false;
      if (!getOfflineMsgsList()
          .equals(other.getOfflineMsgsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + getY().hashCode();
      if (getOfflineMsgsCount() > 0) {
        hash = (37 * hash) + OFFLINEMSGS_FIELD_NUMBER;
        hash = (53 * hash) + getOfflineMsgsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.knilim.session.data.ConnectResponseProto.ConnectResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.knilim.session.data.ConnectResponseProto.ConnectResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.knilim.session.data.ConnectResponseProto.ConnectResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.knilim.session.data.ConnectResponseProto.ConnectResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.knilim.session.data.ConnectResponseProto.ConnectResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.knilim.session.data.ConnectResponseProto.ConnectResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.knilim.session.data.ConnectResponseProto.ConnectResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.knilim.session.data.ConnectResponseProto.ConnectResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.knilim.session.data.ConnectResponseProto.ConnectResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.knilim.session.data.ConnectResponseProto.ConnectResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.knilim.session.data.ConnectResponseProto.ConnectResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.knilim.session.data.ConnectResponseProto.ConnectResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.knilim.session.data.ConnectResponseProto.ConnectResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ConnectResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConnectResponse)
        com.knilim.session.data.ConnectResponseProto.ConnectResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.knilim.session.data.ConnectResponseProto.internal_static_ConnectResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.knilim.session.data.ConnectResponseProto.internal_static_ConnectResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.knilim.session.data.ConnectResponseProto.ConnectResponse.class, com.knilim.session.data.ConnectResponseProto.ConnectResponse.Builder.class);
      }

      // Construct using com.knilim.session.data.ConnectResponseProto.ConnectResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        y_ = "";

        offlineMsgs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.knilim.session.data.ConnectResponseProto.internal_static_ConnectResponse_descriptor;
      }

      @java.lang.Override
      public com.knilim.session.data.ConnectResponseProto.ConnectResponse getDefaultInstanceForType() {
        return com.knilim.session.data.ConnectResponseProto.ConnectResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.knilim.session.data.ConnectResponseProto.ConnectResponse build() {
        com.knilim.session.data.ConnectResponseProto.ConnectResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.knilim.session.data.ConnectResponseProto.ConnectResponse buildPartial() {
        com.knilim.session.data.ConnectResponseProto.ConnectResponse result = new com.knilim.session.data.ConnectResponseProto.ConnectResponse(this);
        int from_bitField0_ = bitField0_;
        result.y_ = y_;
        if (((bitField0_ & 0x00000001) != 0)) {
          offlineMsgs_ = java.util.Collections.unmodifiableList(offlineMsgs_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.offlineMsgs_ = offlineMsgs_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.knilim.session.data.ConnectResponseProto.ConnectResponse) {
          return mergeFrom((com.knilim.session.data.ConnectResponseProto.ConnectResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.knilim.session.data.ConnectResponseProto.ConnectResponse other) {
        if (other == com.knilim.session.data.ConnectResponseProto.ConnectResponse.getDefaultInstance()) return this;
        if (!other.getY().isEmpty()) {
          y_ = other.y_;
          onChanged();
        }
        if (!other.offlineMsgs_.isEmpty()) {
          if (offlineMsgs_.isEmpty()) {
            offlineMsgs_ = other.offlineMsgs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureOfflineMsgsIsMutable();
            offlineMsgs_.addAll(other.offlineMsgs_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.knilim.session.data.ConnectResponseProto.ConnectResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.knilim.session.data.ConnectResponseProto.ConnectResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object y_ = "";
      /**
       * <code>string Y = 1;</code>
       * @return The y.
       */
      public java.lang.String getY() {
        java.lang.Object ref = y_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          y_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Y = 1;</code>
       * @return The bytes for y.
       */
      public com.google.protobuf.ByteString
          getYBytes() {
        java.lang.Object ref = y_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          y_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Y = 1;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Y = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        
        y_ = getDefaultInstance().getY();
        onChanged();
        return this;
      }
      /**
       * <code>string Y = 1;</code>
       * @param value The bytes for y to set.
       * @return This builder for chaining.
       */
      public Builder setYBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        y_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> offlineMsgs_ = java.util.Collections.emptyList();
      private void ensureOfflineMsgsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          offlineMsgs_ = new java.util.ArrayList<com.google.protobuf.ByteString>(offlineMsgs_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes offlineMsgs = 2;</code>
       * @return A list containing the offlineMsgs.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getOfflineMsgsList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(offlineMsgs_) : offlineMsgs_;
      }
      /**
       * <code>repeated bytes offlineMsgs = 2;</code>
       * @return The count of offlineMsgs.
       */
      public int getOfflineMsgsCount() {
        return offlineMsgs_.size();
      }
      /**
       * <code>repeated bytes offlineMsgs = 2;</code>
       * @param index The index of the element to return.
       * @return The offlineMsgs at the given index.
       */
      public com.google.protobuf.ByteString getOfflineMsgs(int index) {
        return offlineMsgs_.get(index);
      }
      /**
       * <code>repeated bytes offlineMsgs = 2;</code>
       * @param index The index to set the value at.
       * @param value The offlineMsgs to set.
       * @return This builder for chaining.
       */
      public Builder setOfflineMsgs(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureOfflineMsgsIsMutable();
        offlineMsgs_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes offlineMsgs = 2;</code>
       * @param value The offlineMsgs to add.
       * @return This builder for chaining.
       */
      public Builder addOfflineMsgs(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureOfflineMsgsIsMutable();
        offlineMsgs_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes offlineMsgs = 2;</code>
       * @param values The offlineMsgs to add.
       * @return This builder for chaining.
       */
      public Builder addAllOfflineMsgs(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureOfflineMsgsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, offlineMsgs_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes offlineMsgs = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOfflineMsgs() {
        offlineMsgs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ConnectResponse)
    }

    // @@protoc_insertion_point(class_scope:ConnectResponse)
    private static final com.knilim.session.data.ConnectResponseProto.ConnectResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.knilim.session.data.ConnectResponseProto.ConnectResponse();
    }

    public static com.knilim.session.data.ConnectResponseProto.ConnectResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConnectResponse>
        PARSER = new com.google.protobuf.AbstractParser<ConnectResponse>() {
      @java.lang.Override
      public ConnectResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConnectResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConnectResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConnectResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.knilim.session.data.ConnectResponseProto.ConnectResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConnectResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConnectResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025ConnectResponse.proto\"1\n\017ConnectRespon" +
      "se\022\t\n\001Y\030\001 \001(\t\022\023\n\013offlineMsgs\030\002 \003(\014B/\n\027co" +
      "m.knilim.session.dataB\024ConnectResponsePr" +
      "otob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ConnectResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ConnectResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConnectResponse_descriptor,
        new java.lang.String[] { "Y", "OfflineMsgs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
