// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Notification.proto

package com.knilim.push.data;

public final class NotiProto {
  private NotiProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NotificationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Notification)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string sender = 1;</code>
     * @return The sender.
     */
    java.lang.String getSender();
    /**
     * <code>string sender = 1;</code>
     * @return The bytes for sender.
     */
    com.google.protobuf.ByteString
        getSenderBytes();

    /**
     * <code>string receiver = 2;</code>
     * @return The receiver.
     */
    java.lang.String getReceiver();
    /**
     * <code>string receiver = 2;</code>
     * @return The bytes for receiver.
     */
    com.google.protobuf.ByteString
        getReceiverBytes();

    /**
     * <code>.Notification.NotiType notificationType = 3;</code>
     * @return The enum numeric value on the wire for notificationType.
     */
    int getNotificationTypeValue();
    /**
     * <code>.Notification.NotiType notificationType = 3;</code>
     * @return The notificationType.
     */
    com.knilim.push.data.NotiProto.Notification.NotiType getNotificationType();

    /**
     * <code>string content = 4;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <code>string content = 4;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>string createAt = 5;</code>
     * @return The createAt.
     */
    java.lang.String getCreateAt();
    /**
     * <code>string createAt = 5;</code>
     * @return The bytes for createAt.
     */
    com.google.protobuf.ByteString
        getCreateAtBytes();
  }
  /**
   * Protobuf type {@code Notification}
   */
  public  static final class Notification extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Notification)
      NotificationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Notification.newBuilder() to construct.
    private Notification(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Notification() {
      sender_ = "";
      receiver_ = "";
      notificationType_ = 0;
      content_ = "";
      createAt_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Notification();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Notification(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              sender_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              receiver_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              notificationType_ = rawValue;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              createAt_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.knilim.push.data.NotiProto.internal_static_Notification_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.knilim.push.data.NotiProto.internal_static_Notification_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.knilim.push.data.NotiProto.Notification.class, com.knilim.push.data.NotiProto.Notification.Builder.class);
    }

    /**
     * Protobuf enum {@code Notification.NotiType}
     */
    public enum NotiType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>N_FRIEND_ADD_APPLICATION = 0;</code>
       */
      N_FRIEND_ADD_APPLICATION(0),
      /**
       * <code>N_FRIEND_ADD_RESULT = 1;</code>
       */
      N_FRIEND_ADD_RESULT(1),
      /**
       * <code>N_FRIEND_DELETE_RESULT = 2;</code>
       */
      N_FRIEND_DELETE_RESULT(2),
      /**
       * <code>N_GROUP_JOIN_APPLICATION = 3;</code>
       */
      N_GROUP_JOIN_APPLICATION(3),
      /**
       * <code>N_GROUP_JOIN_RESULT = 4;</code>
       */
      N_GROUP_JOIN_RESULT(4),
      /**
       * <code>N_GROUP_WITHDRAW_RESULT = 5;</code>
       */
      N_GROUP_WITHDRAW_RESULT(5),
      /**
       * <code>N_GROUP_KICKOFF_RESULT = 6;</code>
       */
      N_GROUP_KICKOFF_RESULT(6),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>N_FRIEND_ADD_APPLICATION = 0;</code>
       */
      public static final int N_FRIEND_ADD_APPLICATION_VALUE = 0;
      /**
       * <code>N_FRIEND_ADD_RESULT = 1;</code>
       */
      public static final int N_FRIEND_ADD_RESULT_VALUE = 1;
      /**
       * <code>N_FRIEND_DELETE_RESULT = 2;</code>
       */
      public static final int N_FRIEND_DELETE_RESULT_VALUE = 2;
      /**
       * <code>N_GROUP_JOIN_APPLICATION = 3;</code>
       */
      public static final int N_GROUP_JOIN_APPLICATION_VALUE = 3;
      /**
       * <code>N_GROUP_JOIN_RESULT = 4;</code>
       */
      public static final int N_GROUP_JOIN_RESULT_VALUE = 4;
      /**
       * <code>N_GROUP_WITHDRAW_RESULT = 5;</code>
       */
      public static final int N_GROUP_WITHDRAW_RESULT_VALUE = 5;
      /**
       * <code>N_GROUP_KICKOFF_RESULT = 6;</code>
       */
      public static final int N_GROUP_KICKOFF_RESULT_VALUE = 6;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static NotiType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static NotiType forNumber(int value) {
        switch (value) {
          case 0: return N_FRIEND_ADD_APPLICATION;
          case 1: return N_FRIEND_ADD_RESULT;
          case 2: return N_FRIEND_DELETE_RESULT;
          case 3: return N_GROUP_JOIN_APPLICATION;
          case 4: return N_GROUP_JOIN_RESULT;
          case 5: return N_GROUP_WITHDRAW_RESULT;
          case 6: return N_GROUP_KICKOFF_RESULT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<NotiType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          NotiType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<NotiType>() {
              public NotiType findValueByNumber(int number) {
                return NotiType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.knilim.push.data.NotiProto.Notification.getDescriptor().getEnumTypes().get(0);
      }

      private static final NotiType[] VALUES = values();

      public static NotiType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private NotiType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Notification.NotiType)
    }

    public static final int SENDER_FIELD_NUMBER = 1;
    private volatile java.lang.Object sender_;
    /**
     * <code>string sender = 1;</code>
     * @return The sender.
     */
    public java.lang.String getSender() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sender_ = s;
        return s;
      }
    }
    /**
     * <code>string sender = 1;</code>
     * @return The bytes for sender.
     */
    public com.google.protobuf.ByteString
        getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVER_FIELD_NUMBER = 2;
    private volatile java.lang.Object receiver_;
    /**
     * <code>string receiver = 2;</code>
     * @return The receiver.
     */
    public java.lang.String getReceiver() {
      java.lang.Object ref = receiver_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiver_ = s;
        return s;
      }
    }
    /**
     * <code>string receiver = 2;</code>
     * @return The bytes for receiver.
     */
    public com.google.protobuf.ByteString
        getReceiverBytes() {
      java.lang.Object ref = receiver_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NOTIFICATIONTYPE_FIELD_NUMBER = 3;
    private int notificationType_;
    /**
     * <code>.Notification.NotiType notificationType = 3;</code>
     * @return The enum numeric value on the wire for notificationType.
     */
    public int getNotificationTypeValue() {
      return notificationType_;
    }
    /**
     * <code>.Notification.NotiType notificationType = 3;</code>
     * @return The notificationType.
     */
    public com.knilim.push.data.NotiProto.Notification.NotiType getNotificationType() {
      @SuppressWarnings("deprecation")
      com.knilim.push.data.NotiProto.Notification.NotiType result = com.knilim.push.data.NotiProto.Notification.NotiType.valueOf(notificationType_);
      return result == null ? com.knilim.push.data.NotiProto.Notification.NotiType.UNRECOGNIZED : result;
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    private volatile java.lang.Object content_;
    /**
     * <code>string content = 4;</code>
     * @return The content.
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 4;</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATEAT_FIELD_NUMBER = 5;
    private volatile java.lang.Object createAt_;
    /**
     * <code>string createAt = 5;</code>
     * @return The createAt.
     */
    public java.lang.String getCreateAt() {
      java.lang.Object ref = createAt_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createAt_ = s;
        return s;
      }
    }
    /**
     * <code>string createAt = 5;</code>
     * @return The bytes for createAt.
     */
    public com.google.protobuf.ByteString
        getCreateAtBytes() {
      java.lang.Object ref = createAt_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSenderBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sender_);
      }
      if (!getReceiverBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, receiver_);
      }
      if (notificationType_ != com.knilim.push.data.NotiProto.Notification.NotiType.N_FRIEND_ADD_APPLICATION.getNumber()) {
        output.writeEnum(3, notificationType_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, content_);
      }
      if (!getCreateAtBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, createAt_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSenderBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sender_);
      }
      if (!getReceiverBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, receiver_);
      }
      if (notificationType_ != com.knilim.push.data.NotiProto.Notification.NotiType.N_FRIEND_ADD_APPLICATION.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, notificationType_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, content_);
      }
      if (!getCreateAtBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, createAt_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.knilim.push.data.NotiProto.Notification)) {
        return super.equals(obj);
      }
      com.knilim.push.data.NotiProto.Notification other = (com.knilim.push.data.NotiProto.Notification) obj;

      if (!getSender()
          .equals(other.getSender())) return false;
      if (!getReceiver()
          .equals(other.getReceiver())) return false;
      if (notificationType_ != other.notificationType_) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!getCreateAt()
          .equals(other.getCreateAt())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SENDER_FIELD_NUMBER;
      hash = (53 * hash) + getSender().hashCode();
      hash = (37 * hash) + RECEIVER_FIELD_NUMBER;
      hash = (53 * hash) + getReceiver().hashCode();
      hash = (37 * hash) + NOTIFICATIONTYPE_FIELD_NUMBER;
      hash = (53 * hash) + notificationType_;
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + CREATEAT_FIELD_NUMBER;
      hash = (53 * hash) + getCreateAt().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.knilim.push.data.NotiProto.Notification parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.knilim.push.data.NotiProto.Notification parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.knilim.push.data.NotiProto.Notification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.knilim.push.data.NotiProto.Notification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.knilim.push.data.NotiProto.Notification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.knilim.push.data.NotiProto.Notification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.knilim.push.data.NotiProto.Notification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.knilim.push.data.NotiProto.Notification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.knilim.push.data.NotiProto.Notification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.knilim.push.data.NotiProto.Notification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.knilim.push.data.NotiProto.Notification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.knilim.push.data.NotiProto.Notification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.knilim.push.data.NotiProto.Notification prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Notification}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Notification)
        com.knilim.push.data.NotiProto.NotificationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.knilim.push.data.NotiProto.internal_static_Notification_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.knilim.push.data.NotiProto.internal_static_Notification_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.knilim.push.data.NotiProto.Notification.class, com.knilim.push.data.NotiProto.Notification.Builder.class);
      }

      // Construct using com.knilim.push.data.NotiProto.Notification.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sender_ = "";

        receiver_ = "";

        notificationType_ = 0;

        content_ = "";

        createAt_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.knilim.push.data.NotiProto.internal_static_Notification_descriptor;
      }

      @java.lang.Override
      public com.knilim.push.data.NotiProto.Notification getDefaultInstanceForType() {
        return com.knilim.push.data.NotiProto.Notification.getDefaultInstance();
      }

      @java.lang.Override
      public com.knilim.push.data.NotiProto.Notification build() {
        com.knilim.push.data.NotiProto.Notification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.knilim.push.data.NotiProto.Notification buildPartial() {
        com.knilim.push.data.NotiProto.Notification result = new com.knilim.push.data.NotiProto.Notification(this);
        result.sender_ = sender_;
        result.receiver_ = receiver_;
        result.notificationType_ = notificationType_;
        result.content_ = content_;
        result.createAt_ = createAt_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.knilim.push.data.NotiProto.Notification) {
          return mergeFrom((com.knilim.push.data.NotiProto.Notification)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.knilim.push.data.NotiProto.Notification other) {
        if (other == com.knilim.push.data.NotiProto.Notification.getDefaultInstance()) return this;
        if (!other.getSender().isEmpty()) {
          sender_ = other.sender_;
          onChanged();
        }
        if (!other.getReceiver().isEmpty()) {
          receiver_ = other.receiver_;
          onChanged();
        }
        if (other.notificationType_ != 0) {
          setNotificationTypeValue(other.getNotificationTypeValue());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (!other.getCreateAt().isEmpty()) {
          createAt_ = other.createAt_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.knilim.push.data.NotiProto.Notification parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.knilim.push.data.NotiProto.Notification) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object sender_ = "";
      /**
       * <code>string sender = 1;</code>
       * @return The sender.
       */
      public java.lang.String getSender() {
        java.lang.Object ref = sender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sender_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sender = 1;</code>
       * @return The bytes for sender.
       */
      public com.google.protobuf.ByteString
          getSenderBytes() {
        java.lang.Object ref = sender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sender = 1;</code>
       * @param value The sender to set.
       * @return This builder for chaining.
       */
      public Builder setSender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sender = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSender() {
        
        sender_ = getDefaultInstance().getSender();
        onChanged();
        return this;
      }
      /**
       * <code>string sender = 1;</code>
       * @param value The bytes for sender to set.
       * @return This builder for chaining.
       */
      public Builder setSenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sender_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object receiver_ = "";
      /**
       * <code>string receiver = 2;</code>
       * @return The receiver.
       */
      public java.lang.String getReceiver() {
        java.lang.Object ref = receiver_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiver_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string receiver = 2;</code>
       * @return The bytes for receiver.
       */
      public com.google.protobuf.ByteString
          getReceiverBytes() {
        java.lang.Object ref = receiver_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiver_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string receiver = 2;</code>
       * @param value The receiver to set.
       * @return This builder for chaining.
       */
      public Builder setReceiver(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiver_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string receiver = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearReceiver() {
        
        receiver_ = getDefaultInstance().getReceiver();
        onChanged();
        return this;
      }
      /**
       * <code>string receiver = 2;</code>
       * @param value The bytes for receiver to set.
       * @return This builder for chaining.
       */
      public Builder setReceiverBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiver_ = value;
        onChanged();
        return this;
      }

      private int notificationType_ = 0;
      /**
       * <code>.Notification.NotiType notificationType = 3;</code>
       * @return The enum numeric value on the wire for notificationType.
       */
      public int getNotificationTypeValue() {
        return notificationType_;
      }
      /**
       * <code>.Notification.NotiType notificationType = 3;</code>
       * @param value The enum numeric value on the wire for notificationType to set.
       * @return This builder for chaining.
       */
      public Builder setNotificationTypeValue(int value) {
        notificationType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Notification.NotiType notificationType = 3;</code>
       * @return The notificationType.
       */
      public com.knilim.push.data.NotiProto.Notification.NotiType getNotificationType() {
        @SuppressWarnings("deprecation")
        com.knilim.push.data.NotiProto.Notification.NotiType result = com.knilim.push.data.NotiProto.Notification.NotiType.valueOf(notificationType_);
        return result == null ? com.knilim.push.data.NotiProto.Notification.NotiType.UNRECOGNIZED : result;
      }
      /**
       * <code>.Notification.NotiType notificationType = 3;</code>
       * @param value The notificationType to set.
       * @return This builder for chaining.
       */
      public Builder setNotificationType(com.knilim.push.data.NotiProto.Notification.NotiType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        notificationType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Notification.NotiType notificationType = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNotificationType() {
        
        notificationType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>string content = 4;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content = 4;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 4;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 4;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object createAt_ = "";
      /**
       * <code>string createAt = 5;</code>
       * @return The createAt.
       */
      public java.lang.String getCreateAt() {
        java.lang.Object ref = createAt_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          createAt_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string createAt = 5;</code>
       * @return The bytes for createAt.
       */
      public com.google.protobuf.ByteString
          getCreateAtBytes() {
        java.lang.Object ref = createAt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          createAt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string createAt = 5;</code>
       * @param value The createAt to set.
       * @return This builder for chaining.
       */
      public Builder setCreateAt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        createAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string createAt = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreateAt() {
        
        createAt_ = getDefaultInstance().getCreateAt();
        onChanged();
        return this;
      }
      /**
       * <code>string createAt = 5;</code>
       * @param value The bytes for createAt to set.
       * @return This builder for chaining.
       */
      public Builder setCreateAtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        createAt_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Notification)
    }

    // @@protoc_insertion_point(class_scope:Notification)
    private static final com.knilim.push.data.NotiProto.Notification DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.knilim.push.data.NotiProto.Notification();
    }

    public static com.knilim.push.data.NotiProto.Notification getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Notification>
        PARSER = new com.google.protobuf.AbstractParser<Notification>() {
      @java.lang.Override
      public Notification parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Notification(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Notification> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Notification> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.knilim.push.data.NotiProto.Notification getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Notification_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Notification_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022Notification.proto\"\325\002\n\014Notification\022\016\n" +
      "\006sender\030\001 \001(\t\022\020\n\010receiver\030\002 \001(\t\0220\n\020notif" +
      "icationType\030\003 \001(\0162\026.Notification.NotiTyp" +
      "e\022\017\n\007content\030\004 \001(\t\022\020\n\010createAt\030\005 \001(\t\"\315\001\n" +
      "\010NotiType\022\034\n\030N_FRIEND_ADD_APPLICATION\020\000\022" +
      "\027\n\023N_FRIEND_ADD_RESULT\020\001\022\032\n\026N_FRIEND_DEL" +
      "ETE_RESULT\020\002\022\034\n\030N_GROUP_JOIN_APPLICATION" +
      "\020\003\022\027\n\023N_GROUP_JOIN_RESULT\020\004\022\033\n\027N_GROUP_W" +
      "ITHDRAW_RESULT\020\005\022\032\n\026N_GROUP_KICKOFF_RESU" +
      "LT\020\006B!\n\024com.knilim.push.dataB\tNotiProtob" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Notification_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Notification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Notification_descriptor,
        new java.lang.String[] { "Sender", "Receiver", "NotificationType", "Content", "CreateAt", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
